apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
gkeCluster:
  project: paratasso
  cluster: staging
  location: us-central1
